/* Generated by tools/generate_coefficients.py; do not edit numeric literals. */
#pragma once
#include "fixed_vqf.h"

#if FIXED_VQF_SAMPLE_HZ == 2000U
static const q30_t ACC_B_Q30[3] = {15, 30, 15};
static const q30_t ACC_A_Q30[2] = {-2147125734, 1073383970};
static const q30_t REST_B_Q30[3] = {536, 1073, 536};
static const q30_t REST_A_Q30[2] = {-2145336165, 1071596486};
#define REST_MIN_SAMPLES ((uint16_t)3000LL)
#define BIAS_V_Q20 ((int64_t)524LL)
#define BIAS_W_MOTION_Q20 ((int64_t)20971624857600LL)
#define BIAS_W_VERTICAL_Q20 ((int64_t)209716248576000000LL)
#define BIAS_W_REST_Q20 ((int64_t)169878749184LL)
#define GYR_HALF_DT_Q30 ((int64_t)268435LL)
#define MOTION_ACC_RATE_Q32 ((int64_t)8000LL)
#elif FIXED_VQF_SAMPLE_HZ == 1000U
static const q30_t ACC_B_Q30[3] = {60, 119, 60};
static const q30_t ACC_A_Q30[2] = {-2146767820, 1073026235};
static const q30_t REST_B_Q30[3] = {2143, 4287, 2143};
static const q30_t REST_A_Q30[2] = {-2143188686, 1069455435};
#define REST_MIN_SAMPLES ((uint16_t)1500LL)
#define BIAS_V_Q20 ((int64_t)1049LL)
#define BIAS_W_MOTION_Q20 ((int64_t)10485864857600LL)
#define BIAS_W_VERTICAL_Q20 ((int64_t)104858648576000000LL)
#define BIAS_W_REST_Q20 ((int64_t)84944093184LL)
#define GYR_HALF_DT_Q30 ((int64_t)536871LL)
#define MOTION_ACC_RATE_Q32 ((int64_t)4000LL)
#else
#error "FIXED_VQF_SAMPLE_HZ must be 1000 or 2000"
#endif

#define BIAS_CLIP_Q24 ((q24_t)585635LL)
#define BIAS_CLIP_Q32 ((int64_t)149922641LL)
#define REST_GYR_TH_Q24 ((q24_t)585635LL)
#define REST_ACC_TH_Q30 ((q30_t)54726902LL)
#define BIAS_P0_Q20 ((int64_t)2621440000LL)
#define BIAS_P_FLOOR_Q20 ((int64_t)1LL)
