#include "fixed_vqf.h"
#include "imu_numeric.h"

#include <limits.h>
#include <string.h>

#define Q30_ONE                 ((q30_t)0x40000000)
#define Q30_HALF                ((q30_t)0x20000000)
#define Q20_ONE                 ((int64_t)1048576)
#define ABS32U(x)               ((uint32_t)((x) < 0 ? -(int64_t)(x) : (x)))

#include "fixed_vqf_coefficients.h"

#define FLAG_REST               0x0001u
#define FLAG_REST_GYR_INIT      0x0002u
#define FLAG_REST_ACC_INIT      0x0004u
#define FLAG_ACC_LP_INIT        0x0008u
#define FLAG_MOTION_R_INIT      0x0010u
#define FLAG_MOTION_BIAS_INIT   0x0020u

volatile uint32_t fixed_vqf_acc_reject_count = 0U;
volatile uint32_t fixed_vqf_kalman_update_count = 0U;
volatile uint32_t fixed_vqf_kalman_reject_count = 0U;

static inline int32_t sat32(int64_t x)
{
    if (x > INT32_MAX) return INT32_MAX;
    if (x < INT32_MIN) return INT32_MIN;
    return (int32_t)x;
}

static inline int64_t round_shift_s64(int64_t x, uint8_t shift)
{
    int64_t half = (int64_t)1 << (shift - 1U);
    if (x >= 0) return (x + half) >> shift;
    return -(((-x) + half) >> shift);
}

static inline q30_t q30_mul(q30_t a, q30_t b)
{
    return sat32(round_shift_s64((int64_t)a * b, 30U));
}

static inline q24_t q30_mul_q24(q30_t a, q24_t b)
{
    return sat32(round_shift_s64((int64_t)a * b, 30U));
}

static inline int64_t q30_mul_q32(q30_t a, int64_t b)
{
    return round_shift_s64((int64_t)a * b, 30U);
}

/* Multiply a Q1.30 coefficient by a high precision value whose binary
 * point is 30 bits below the Q30 output.  The mathematical product is Q60,
 * but a direct a*y60 multiplication would be Q90 and overflow int64_t. */
static inline int64_t q30_mul_hi_state(q30_t a, int64_t y60)
{
    int64_t y = y60 / (1LL << 30);
    int64_t rem = y60 - y * (1LL << 30);
    return (int64_t)a * y + round_shift_s64((int64_t)a * rem, 30U);
}

/* Signed ratio in Q1.30.  Do not pre-scale both operands: that destroys
 * small Kalman gains.  The fractional part is generated by a restoring
 * long division; the half-denominator test avoids overflowing rem << 1
 * even when the denominator is close to UINT64_MAX. */
static q30_t ratio_s64_q30(int64_t num, int64_t den)
{
    uint64_t un, ud, rem, frac;
    uint32_t integer;
    uint32_t i;
    bool neg;

    if (den == 0) return num >= 0 ? INT32_MAX : INT32_MIN;
    if (num == 0) return 0;
    neg = ((num < 0) != (den < 0));
    /* Unsigned negation is defined, including INT64_MIN. */
    un = num < 0 ? (0ULL - (uint64_t)num) : (uint64_t)num;
    ud = den < 0 ? (0ULL - (uint64_t)den) : (uint64_t)den;
    if (ud == 0U) return neg ? INT32_MIN : INT32_MAX;

    /* Only quotient 0/1 is usable (>=2 saturates), so subtract instead of
     * dividing: identical integer/rem without libgcc __udivdi3/__umoddi3. */
    integer = 0U;
    rem = un;
    if (rem >= ud) {
        rem -= ud;
        if (rem >= ud) return neg ? INT32_MIN : INT32_MAX;
        integer = 1U;
    }

    frac = 0U;
    for (i = 0U; i < 30U; ++i) {
        /* If 2*rem >= ud, subtract before doubling to remain in range. */
        if (rem >= ((ud >> 1U) + (ud & 1U))) {
            rem = (rem - ud) + rem;
            frac = (frac << 1U) | 1U;
        } else {
            rem += rem;
            frac <<= 1U;
        }
    }
    {
        uint64_t uq = ((uint64_t)integer << 30U) | frac;
        if (uq > 0x7fffffffULL) uq = 0x7fffffffULL;
        return neg ? -(q30_t)uq : (q30_t)uq;
    }
}

static uint32_t isqrt_u64(uint64_t value)
{
    uint64_t bit = (uint64_t)1U << 62;
    uint64_t result = 0U;
    while (bit > value) bit >>= 2;
    while (bit != 0U) {
        if (value >= result + bit) {
            value -= result + bit;
            result = (result >> 1) + bit;
        } else {
            result >>= 1;
        }
        bit >>= 2;
    }
    return (uint32_t)result;
}

static q30_t invsqrt_near1_q30(q30_t x)
{
    q30_t y = Q30_ONE;
    uint32_t i;
    for (i = 0U; i < 3U; ++i) {
        q30_t y2 = q30_mul(y, y);
        q30_t xy2 = q30_mul(x, y2);
        q30_t k = sat32(((int64_t)3 * Q30_ONE - xy2) >> 1);
        y = q30_mul(y, k);
    }
    return y;
}

static bool normalize_q30(q30_t v[], uint32_t n)
{
    uint64_t sum = 0U;
    uint32_t i;
    for (i = 0U; i < n; ++i) sum += (uint64_t)((int64_t)v[i] * v[i]);
    if (sum == 0U) return false;

    /* Fast high-accuracy path for all normal VQF vectors. */
    {
        int64_t norm2_q30 = round_shift_s64((int64_t)sum, 30U);
        if (norm2_q30 >= (Q30_ONE >> 2) && norm2_q30 <= (Q30_ONE + (Q30_ONE >> 1))) {
            q30_t inv = invsqrt_near1_q30((q30_t)norm2_q30);
            for (i = 0U; i < n; ++i) v[i] = q30_mul(v[i], inv);
            return true;
        }
    }

    /* Rare startup/fault fallback: exact integer sqrt plus M-extension ratio. */
    {
        uint32_t norm_q30 = isqrt_u64(sum);
        if (norm_q30 == 0U) return false;
        for (i = 0U; i < n; ++i) v[i] = ratio_s64_q30(v[i], norm_q30);
    }
    return true;
}

static void quat_mul(const q30_t a[4], const q30_t b[4], q30_t o[4])
{
    int64_t w = (int64_t)a[0]*b[0] - (int64_t)a[1]*b[1] - (int64_t)a[2]*b[2] - (int64_t)a[3]*b[3];
    int64_t x = (int64_t)a[0]*b[1] + (int64_t)a[1]*b[0] + (int64_t)a[2]*b[3] - (int64_t)a[3]*b[2];
    int64_t y = (int64_t)a[0]*b[2] - (int64_t)a[1]*b[3] + (int64_t)a[2]*b[0] + (int64_t)a[3]*b[1];
    int64_t z = (int64_t)a[0]*b[3] + (int64_t)a[1]*b[2] - (int64_t)a[2]*b[1] + (int64_t)a[3]*b[0];
    o[0] = sat32(round_shift_s64(w, 30U));
    o[1] = sat32(round_shift_s64(x, 30U));
    o[2] = sat32(round_shift_s64(y, 30U));
    o[3] = sat32(round_shift_s64(z, 30U));
}

static void quat_to_R(const q30_t q[4], q30_t R[9]);

static void quat_rotate(const q30_t q[4], const q30_t v[3], q30_t out[3])
{
    q30_t R[9];
    quat_to_R(q,R);
    out[0]=sat32((int64_t)q30_mul(R[0],v[0])+q30_mul(R[1],v[1])+q30_mul(R[2],v[2]));
    out[1]=sat32((int64_t)q30_mul(R[3],v[0])+q30_mul(R[4],v[1])+q30_mul(R[5],v[2]));
    out[2]=sat32((int64_t)q30_mul(R[6],v[0])+q30_mul(R[7],v[1])+q30_mul(R[8],v[2]));
}

static void quat_to_R(const q30_t q[4], q30_t R[9])
{
    q30_t q0=q[0], q1=q[1], q2=q[2], q3=q[3];
    R[0]=sat32((int64_t)Q30_ONE-2LL*q30_mul(q2,q2)-2LL*q30_mul(q3,q3));
    R[1]=sat32(2LL*((int64_t)q30_mul(q2,q1)-q30_mul(q0,q3)));
    R[2]=sat32(2LL*((int64_t)q30_mul(q0,q2)+q30_mul(q3,q1)));
    R[3]=sat32(2LL*((int64_t)q30_mul(q0,q3)+q30_mul(q2,q1)));
    R[4]=sat32((int64_t)Q30_ONE-2LL*q30_mul(q1,q1)-2LL*q30_mul(q3,q3));
    R[5]=sat32(2LL*((int64_t)q30_mul(q2,q3)-q30_mul(q1,q0)));
    R[6]=sat32(2LL*((int64_t)q30_mul(q3,q1)-q30_mul(q0,q2)));
    R[7]=sat32(2LL*((int64_t)q30_mul(q0,q1)+q30_mul(q3,q2)));
    R[8]=sat32((int64_t)Q30_ONE-2LL*q30_mul(q1,q1)-2LL*q30_mul(q2,q2));
}

static void filter_init_q30(q30_t x, const q30_t b[3], const q30_t a[2], int64_t st[2])
{
    st[0] = (int64_t)x * (Q30_ONE - b[0]);
    st[1] = (int64_t)x * (b[2] - a[1]);
}

static q30_t filter_step_q30(q30_t x, const q30_t b[3], const q30_t a[2], int64_t st[2])
{
    int64_t y60 = (int64_t)b[0]*x + st[0];
    q30_t y = sat32(round_shift_s64(y60, 30U));
    int64_t y_fb0 = q30_mul_hi_state(a[0], y60);
    int64_t y_fb1 = q30_mul_hi_state(a[1], y60);
    int64_t s0 = (int64_t)b[1]*x - y_fb0 + st[1];
    int64_t s1 = (int64_t)b[2]*x - y_fb1;
    st[0]=s0; st[1]=s1;
    return y;
}

static void filter_init_q24(q24_t x, const q30_t b[3], const q30_t a[2], int64_t st[2])
{
    st[0] = (int64_t)x * (Q30_ONE - b[0]);
    st[1] = (int64_t)x * (b[2] - a[1]);
}

static q24_t filter_step_q24(q24_t x, const q30_t b[3], const q30_t a[2], int64_t st[2])
{
    int64_t y54 = (int64_t)b[0]*x + st[0];
    q24_t y = sat32(round_shift_s64(y54, 30U));
    int64_t y_fb0 = q30_mul_hi_state(a[0], y54);
    int64_t y_fb1 = q30_mul_hi_state(a[1], y54);
    int64_t s0 = (int64_t)b[1]*x - y_fb0 + st[1];
    int64_t s1 = (int64_t)b[2]*x - y_fb1;
    st[0]=s0; st[1]=s1;
    return y;
}

static void filter_init_q32(int64_t x, const q30_t b[3], const q30_t a[2], int64_t st[2])
{
    st[0] = x * (Q30_ONE - b[0]);
    st[1] = x * (b[2] - a[1]);
}

static int64_t filter_step_q32(int64_t x, const q30_t b[3], const q30_t a[2], int64_t st[2])
{
    int64_t y62 = (int64_t)b[0]*x + st[0];
    int64_t y = round_shift_s64(y62, 30U);
    int64_t y_fb0 = q30_mul_hi_state(a[0], y62);
    int64_t y_fb1 = q30_mul_hi_state(a[1], y62);
    int64_t s0 = (int64_t)b[1]*x - y_fb0 + st[1];
    int64_t s1 = (int64_t)b[2]*x - y_fb1;
    st[0]=s0; st[1]=s1;
    return y;
}
static void filter_vec_q30(fixed_vqf_t *s, const q30_t *x, uint32_t n,
                                     const q30_t b[3], const q30_t a[2], int64_t *st,
                                     q30_t *out, uint16_t init_flag)
{
    uint32_t i;
    if ((s->flags & init_flag) == 0U) {
        for (i=0U; i<n; ++i) { filter_init_q30(x[i],b,a,&st[2U*i]); out[i]=x[i]; }
        s->flags |= init_flag;
        return;
    }
    for (i=0U; i<n; ++i) out[i]=filter_step_q30(x[i],b,a,&st[2U*i]);
}

static void filter_vec_q24(fixed_vqf_t *s, const q24_t *x, uint32_t n,
                                     const q30_t b[3], const q30_t a[2], int64_t *st,
                                     q24_t *out, uint16_t init_flag)
{
    uint32_t i;
    if ((s->flags & init_flag) == 0U) {
        for (i=0U; i<n; ++i) { filter_init_q24(x[i],b,a,&st[2U*i]); out[i]=x[i]; }
        s->flags |= init_flag;
        return;
    }
    for (i=0U; i<n; ++i) out[i]=filter_step_q24(x[i],b,a,&st[2U*i]);
}

static void filter_vec_q32(fixed_vqf_t *s, const int64_t *x, uint32_t n,
                                     const q30_t b[3], const q30_t a[2], int64_t *st,
                                     int64_t *out, uint16_t init_flag)
{
    uint32_t i;
    if ((s->flags & init_flag) == 0U) {
        for (i=0U; i<n; ++i) { filter_init_q32(x[i],b,a,&st[2U*i]); out[i]=x[i]; }
        s->flags |= init_flag;
        return;
    }
    for (i=0U; i<n; ++i) out[i]=filter_step_q32(x[i],b,a,&st[2U*i]);
}
static void get_quat6d(const fixed_vqf_t *s, q30_t out[4])
{
    quat_mul(s->acc_q, s->gyr_q, out);
}

/* Sequential scalar Kalman measurements are algebraically equivalent to the
 * Full VQF 3x3 update for diagonal W, but avoid a poorly conditioned fixed-point
 * matrix inverse. Bias is Q32; P and W are Q20; H and K are Q30. */
static void bias_kalman_update(fixed_vqf_t *s, const q30_t H[9],
                                         const int64_t e0[3], const int64_t W[3])
{
    const int64_t bias_start[3] = {s->gyro_bias_q32[0],s->gyro_bias_q32[1],s->gyro_bias_q32[2]};
    uint32_t meas;

    for (meas=0U; meas<3U; ++meas) {
        int64_t ph[3];
        q30_t K[3];
        int64_t den;
        int64_t e;
        uint32_t r,c,k;

        /* Recompute the residual after prior scalar measurements. */
        e = e0[meas];
        for (k=0U; k<3U; ++k) {
            e -= q30_mul_q32(H[meas*3U+k], s->gyro_bias_q32[k]-bias_start[k]);
        }

        for (r=0U; r<3U; ++r) {
            int64_t v=0;
            for (k=0U; k<3U; ++k) v += round_shift_s64(s->bias_P_q20[r*3U+k]*H[meas*3U+k],30U);
            ph[r]=v;
        }
        den=W[meas];
        for (k=0U; k<3U; ++k) den += round_shift_s64((int64_t)H[meas*3U+k]*ph[k],30U);
        if (den <= 0) { fixed_vqf_kalman_reject_count++; continue; }
        for (r=0U; r<3U; ++r) K[r]=ratio_s64_q30(ph[r],den);

        for (r=0U; r<3U; ++r) {
            s->gyro_bias_q32[r] += q30_mul_q32(K[r],e);
            if (s->gyro_bias_q32[r] > BIAS_CLIP_Q32) s->gyro_bias_q32[r]=BIAS_CLIP_Q32;
            else if (s->gyro_bias_q32[r] < -BIAS_CLIP_Q32) s->gyro_bias_q32[r]=-BIAS_CLIP_Q32;
        }
        for (r=0U; r<3U; ++r) for (c=0U; c<3U; ++c) {
            s->bias_P_q20[r*3U+c] -= round_shift_s64((int64_t)K[r]*ph[c],30U);
        }
    }

    /* Suppress fixed-point asymmetry and retain a positive diagonal. */
    {
        uint32_t r,c;
        for (r=0U; r<3U; ++r) {
            if (s->bias_P_q20[r*3U+r] < BIAS_P_FLOOR_Q20) s->bias_P_q20[r*3U+r]=BIAS_P_FLOOR_Q20;
            if (s->bias_P_q20[r*3U+r] > BIAS_P0_Q20) s->bias_P_q20[r*3U+r]=BIAS_P0_Q20;
            for (c=r+1U; c<3U; ++c) {
                int64_t avg=(s->bias_P_q20[r*3U+c]+s->bias_P_q20[c*3U+r])/2;
                s->bias_P_q20[r*3U+c]=avg;
                s->bias_P_q20[c*3U+r]=avg;
            }
        }
    }
    fixed_vqf_kalman_update_count++;
}

q24_t fixed_vqf_gyro_raw_to_q24(int16_t raw)
{
#if LSM6DSV_GYRO_FS_2000DPS
    /* 0.070 dps/LSB (+/-2000 dps), rad/s in Q40. */
    return sat32(round_shift_s64((int64_t)raw * 1343306864LL, 16U));
#else
    /* 0.004375 dps/LSB (+/-125 dps), rad/s in Q40. */
    return sat32(round_shift_s64((int64_t)raw * 83956679LL, 16U));
#endif
}

void fixed_vqf_init(fixed_vqf_t *s)
{
    memset(s, 0, sizeof(*s));
    s->gyr_q[0]=Q30_ONE;
    s->acc_q[0]=Q30_ONE;
    s->bias_P_q20[0]=BIAS_P0_Q20;
    s->bias_P_q20[4]=BIAS_P0_Q20;
    s->bias_P_q20[8]=BIAS_P0_Q20;
}

void fixed_vqf_update_gyr(fixed_vqf_t *s, const q24_t gyr_rads_q24[3])
{
    const q30_t *b=REST_B_Q30, *a=REST_A_Q30;
    int64_t w_q32[3];
    q30_t h[3];
    q30_t dq[4];
    q30_t nq[4];
    int64_t dev2=0;
    uint32_t i;

    filter_vec_q24(s,gyr_rads_q24,3U,b,a,s->rest_gyr_state_q54,s->rest_last_gyr_q24,FLAG_REST_GYR_INIT);
    for (i=0U; i<3U; ++i) {
        int64_t d=(int64_t)gyr_rads_q24[i]-s->rest_last_gyr_q24[i];
        /* Only the threshold comparison matters. Bound each difference
         * before squaring, including an INT32_MIN/MAX input transition. */
        if (d >= REST_GYR_TH_Q24 || d <= -REST_GYR_TH_Q24) {
            dev2 = (int64_t)REST_GYR_TH_Q24 * REST_GYR_TH_Q24;
            break;
        }
        dev2 += d*d;
    }
    if (dev2 >= (int64_t)REST_GYR_TH_Q24*REST_GYR_TH_Q24 ||
        ABS32U(s->rest_last_gyr_q24[0])>(uint32_t)BIAS_CLIP_Q24 ||
        ABS32U(s->rest_last_gyr_q24[1])>(uint32_t)BIAS_CLIP_Q24 ||
        ABS32U(s->rest_last_gyr_q24[2])>(uint32_t)BIAS_CLIP_Q24) {
        s->rest_count=0U;
        s->flags &= (uint16_t)~FLAG_REST;
    }

    for (i=0U; i<3U; ++i) {
        /* Rest detection is only for bias estimation.  Keep the internal
         * quaternion integration continuous; output-layer yaw hold, when
         * explicitly enabled, must not alter VQF state. */
        w_q32[i] = (int64_t)gyr_rads_q24[i] * 256LL - s->gyro_bias_q32[i];
    }
    /* h = omega*Ts/2. Taylor terms below match sin/cos through fourth order. */
    for (i=0U; i<3U; ++i) h[i]=sat32(round_shift_s64(w_q32[i]*GYR_HALF_DT_Q30,32U));
    {
        q30_t h2=sat32((int64_t)q30_mul(h[0],h[0])+q30_mul(h[1],h[1])+q30_mul(h[2],h[2]));
        q30_t h4=q30_mul(h2,h2);
        q30_t sinc=Q30_ONE-h2/6+h4/120;
        dq[0]=Q30_ONE-h2/2+h4/24;
        dq[1]=q30_mul(h[0],sinc);
        dq[2]=q30_mul(h[1],sinc);
        dq[3]=q30_mul(h[2],sinc);
    }
    quat_mul(s->gyr_q,dq,nq);
    for (i=0U; i<4U; ++i) s->gyr_q[i]=nq[i];
    (void)normalize_q30(s->gyr_q,4U);
}

void fixed_vqf_update_acc(fixed_vqf_t *s, const q30_t acc_g_q30[3])
{
    const q30_t *rb=REST_B_Q30, *ra=REST_A_Q30;
    const q30_t *ab=ACC_B_Q30, *aa=ACC_A_Q30;
    q30_t accEarth[3];
    q30_t corr[4];
    q30_t nq[4];
#if FIXED_VQF_MOTION_BIAS_ENABLED
    q30_t accGyr[4];
    int64_t biasLpIn[2];
    int64_t biasLp[2];
#endif
    q30_t R[9];
    int64_t e[3];
    int64_t W[3];
    int64_t adev2=0;
    uint32_t i;

    if ((acc_g_q30[0]|acc_g_q30[1]|acc_g_q30[2])==0) return;

    filter_vec_q30(s,acc_g_q30,3U,rb,ra,s->rest_acc_state_q60,s->rest_last_acc_q30,FLAG_REST_ACC_INIT);
    for (i=0U; i<3U; ++i) {
        int64_t d=(int64_t)acc_g_q30[i]-s->rest_last_acc_q30[i];
        uint64_t ad = (uint64_t)(d < 0 ? -d : d);
        uint64_t limit = (uint64_t)REST_ACC_TH_Q30;
        if (ad >= limit) {
            adev2 = (int64_t)limit * (int64_t)limit;
            break;
        }
        adev2 += (int64_t)(ad * ad);
    }
    if (adev2 >= (int64_t)REST_ACC_TH_Q30*REST_ACC_TH_Q30) {
        s->rest_count=0U;
        s->flags &= (uint16_t)~FLAG_REST;
    } else {
        if (s->rest_count < REST_MIN_SAMPLES) s->rest_count++;
        if (s->rest_count >= REST_MIN_SAMPLES) s->flags |= FLAG_REST;
    }

    quat_rotate(s->gyr_q,acc_g_q30,accEarth);
    filter_vec_q30(s,accEarth,3U,ab,aa,s->acc_lp_state_q60,s->last_acc_lp_q30,FLAG_ACC_LP_INIT);
    quat_rotate(s->acc_q,s->last_acc_lp_q30,accEarth);
    if (!normalize_q30(accEarth,3U)) { fixed_vqf_acc_reject_count++; return; }

    /* Exact Full-VQF inclination correction, represented by the equivalent
     * normalized quaternion [1+z, y, -x, 0]. */
    if (accEarth[2] < -Q30_ONE+1024) {
        corr[0]=0; corr[1]=Q30_ONE; corr[2]=0; corr[3]=0;
    } else {
        corr[0]=(Q30_ONE>>1)+imu_asr32(accEarth[2],1U);
        corr[1]=imu_asr32(accEarth[1],1U);
        corr[2]=-imu_asr32(accEarth[0],1U);
        corr[3]=0;
        if (!normalize_q30(corr,4U)) { fixed_vqf_acc_reject_count++; return; }
    }
    quat_mul(corr,s->acc_q,nq);
    for (i=0U; i<4U; ++i) s->acc_q[i]=nq[i];
    if (!normalize_q30(s->acc_q,4U)) { fixed_vqf_acc_reject_count++; return; }

    /* Bias estimator configuration is intentionally identical to float VQF. */
#if FIXED_VQF_MOTION_BIAS_ENABLED
    get_quat6d(s,accGyr);
    quat_to_R(accGyr,R);
    biasLpIn[0]=q30_mul_q32(R[0],s->gyro_bias_q32[0])+
                    q30_mul_q32(R[1],s->gyro_bias_q32[1])+q30_mul_q32(R[2],s->gyro_bias_q32[2]);
    biasLpIn[1]=q30_mul_q32(R[3],s->gyro_bias_q32[0])+
                    q30_mul_q32(R[4],s->gyro_bias_q32[1])+q30_mul_q32(R[5],s->gyro_bias_q32[2]);
    filter_vec_q30(s,R,9U,ab,aa,s->motion_R_state_q60,R,FLAG_MOTION_R_INIT);
    filter_vec_q32(s,biasLpIn,2U,ab,aa,s->motion_bias_state_q62,biasLp,FLAG_MOTION_BIAS_INIT);
#endif

    for (i=0U; i<3U; ++i) {
        if (s->bias_P_q20[i*3U+i] < BIAS_P0_Q20) {
            s->bias_P_q20[i*3U+i] += BIAS_V_Q20;
            if (s->bias_P_q20[i*3U+i] > BIAS_P0_Q20) s->bias_P_q20[i*3U+i]=BIAS_P0_Q20;
        }
    }

    if ((s->flags & FLAG_REST) != 0U) {
        for (i=0U; i<9U; ++i) R[i]=0;
        R[0]=R[4]=R[8]=Q30_ONE;
        for (i=0U; i<3U; ++i) {
            e[i]=(int64_t)s->rest_last_gyr_q24[i] * 256LL-s->gyro_bias_q32[i];
            W[i]=BIAS_W_REST_Q20;
        }
    }
#if FIXED_VQF_MOTION_BIAS_ENABLED
    else {
        int64_t er0=-(int64_t)accEarth[1]*MOTION_ACC_RATE_Q32;
        int64_t er1= (int64_t)accEarth[0]*MOTION_ACC_RATE_Q32;
        e[0]=er0+biasLp[0]-q30_mul_q32(R[0],s->gyro_bias_q32[0])-
                   q30_mul_q32(R[1],s->gyro_bias_q32[1])-q30_mul_q32(R[2],s->gyro_bias_q32[2]);
        e[1]=er1+biasLp[1]-q30_mul_q32(R[3],s->gyro_bias_q32[0])-
                   q30_mul_q32(R[4],s->gyro_bias_q32[1])-q30_mul_q32(R[5],s->gyro_bias_q32[2]);
        e[2]=-q30_mul_q32(R[6],s->gyro_bias_q32[0])-
                   q30_mul_q32(R[7],s->gyro_bias_q32[1])-q30_mul_q32(R[8],s->gyro_bias_q32[2]);
        W[0]=BIAS_W_MOTION_Q20;
        W[1]=BIAS_W_MOTION_Q20;
        W[2]=BIAS_W_VERTICAL_Q20;
    }
#endif
#if !FIXED_VQF_MOTION_BIAS_ENABLED
    /* Float VQF uses w=-1 outside rest when motion bias is disabled. */
    if ((s->flags & FLAG_REST) == 0U) return;
#endif
    for (i=0U; i<3U; ++i) {
        if (e[i]>BIAS_CLIP_Q32) e[i]=BIAS_CLIP_Q32;
        else if (e[i]<-BIAS_CLIP_Q32) e[i]=-BIAS_CLIP_Q32;
    }
    bias_kalman_update(s,R,e,W);
}

void fixed_vqf_get_q30(const fixed_vqf_t *s, q30_t out[4])
{
    get_quat6d(s,out);
}

void fixed_vqf_get_bias_q24(const fixed_vqf_t *s, q24_t out[3])
{
    out[0]=sat32(round_shift_s64(s->gyro_bias_q32[0],8U)); out[1]=sat32(round_shift_s64(s->gyro_bias_q32[1],8U)); out[2]=sat32(round_shift_s64(s->gyro_bias_q32[2],8U));
}

void fixed_vqf_get_bias_q16(const fixed_vqf_t *s, int32_t out[3])
{
    out[0]=sat32(round_shift_s64(s->gyro_bias_q32[0],16U));
    out[1]=sat32(round_shift_s64(s->gyro_bias_q32[1],16U));
    out[2]=sat32(round_shift_s64(s->gyro_bias_q32[2],16U));
}

bool fixed_vqf_get_rest_detected(const fixed_vqf_t *s)
{
    return (s->flags & FLAG_REST) != 0U;
}
