"""Generate fixed-point coefficients from the original VQF 6D defaults."""
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
# https://vqf.readthedocs.io/en/latest/ref_cpp_params.html
DEFAULTS = dict(tauAcc=3.0, restFilterTau=0.5, restMinT=1.5,
                restThGyr=2.0, restThAcc=0.5, biasSigmaInit=0.5,
                biasSigmaMotion=0.1, biasSigmaRest=0.03, biasClip=2.0,
                biasForgettingTime=100.0, biasVerticalForgettingFactor=0.0001)

def coefficients(tau, hz):
    c = math.tan(1 / hz / (math.sqrt(2) * tau))
    d = 1 + math.sqrt(2) * c + c*c
    b0 = round(c*c / d * 2**30)
    a1 = round(2 * (c*c - 1) / d * 2**30)
    a2 = round((1 - math.sqrt(2)*c + c*c) / d * 2**30)
    b1 = 2**30 + a1 + a2 - 2*b0  # Preserve unit DC gain after quantization.
    assert -2**30 < a2 < 2**30 and 2**30+a1+a2 > 0 and 2**30-a1+a2 > 0
    return [b0, b1, b0], [a1, a2]

def generate():
    p = DEFAULTS
    lines = ['/* Generated by tools/generate_coefficients.py; do not edit numeric literals. */',
             '#pragma once', '#include "fixed_vqf.h"', '']
    for hz in (2000, 1000):
        lines.append(('#if' if hz == 2000 else '#elif') + f' FIXED_VQF_SAMPLE_HZ == {hz}U')
        for name, tau in (('ACC', p['tauAcc']), ('REST', p['restFilterTau'])):
            b, a = coefficients(tau, hz)
            lines.append(f'static const q30_t {name}_B_Q30[3] = '+'{'+', '.join(map(str, b))+'};')
            lines.append(f'static const q30_t {name}_A_Q30[2] = '+'{'+', '.join(map(str, a))+'};')
        bias_v = (0.1*100)**2 / hz / p['biasForgettingTime']
        p_motion = (p['biasSigmaMotion']*100)**2
        p_rest = (p['biasSigmaRest']*100)**2
        w_motion = p_motion*p_motion / bias_v + p_motion
        values = dict(REST_MIN_SAMPLES=round(p['restMinT']*hz),
                      BIAS_V_Q20=round(bias_v*2**20),
                      BIAS_W_MOTION_Q20=round(w_motion*2**20),
                      BIAS_W_VERTICAL_Q20=round(w_motion/p['biasVerticalForgettingFactor']*2**20),
                      BIAS_W_REST_Q20=round((p_rest*p_rest/bias_v+p_rest)*2**20),
                      GYR_HALF_DT_Q30=round(2**30/(2*hz)), MOTION_ACC_RATE_Q32=4*hz)
        for name, value in values.items():
            ctype = 'uint16_t' if name == 'REST_MIN_SAMPLES' else 'int64_t'
            lines.append(f'#define {name} (({ctype}){value}LL)')
    lines += ['#else', '#error "FIXED_VQF_SAMPLE_HZ must be 1000 or 2000"', '#endif', '']
    constants = dict(BIAS_CLIP_Q24=('q24_t', round(math.radians(p['biasClip'])*2**24)),
                     BIAS_CLIP_Q32=('int64_t', round(math.radians(p['biasClip'])*2**32)),
                     REST_GYR_TH_Q24=('q24_t', round(math.radians(p['restThGyr'])*2**24)),
                     REST_ACC_TH_Q30=('q30_t', round(p['restThAcc']/9.81*2**30)),
                     BIAS_P0_Q20=('int64_t', round((p['biasSigmaInit']*100)**2*2**20)))
    for name, (ctype, value) in constants.items():
        lines.append(f'#define {name} (({ctype}){value}LL)')
    lines += ['#define BIAS_P_FLOOR_Q20 ((int64_t)1LL)', '']
    return '\n'.join(lines)

if __name__ == '__main__':
    (ROOT / 'vqf/c/fixed_vqf_coefficients.h').write_text(generate(), encoding='utf-8', newline='\n')
