"""Generate deterministic fixed-point VQF profile coefficients (no target floats)."""
import math,json
from pathlib import Path
ROOT=Path(__file__).resolve().parent.parent
PROFILES=[dict(id=0,name='fast',tau_acc_s=1.0,bias_sigma_rest_dps=.03,gyro_lpf_hz=120),dict(id=1,name='balanced',tau_acc_s=2.5,bias_sigma_rest_dps=.02,gyro_lpf_hz=80),dict(id=2,name='stable',tau_acc_s=5.0,bias_sigma_rest_dps=.01,gyro_lpf_hz=40)]
def coefficients(tau,hz):
 c=math.tan(1/hz/(math.sqrt(2)*tau));d=1+math.sqrt(2)*c+c*c
 b0=round(c*c/d*2**30);a1=round(2*(c*c-1)/d*2**30);a2=round((1-math.sqrt(2)*c+c*c)/d*2**30)
 # Keep unit DC gain after rounding; important for the motion R/bias LPFs.
 b1=2**30+a1+a2-2*b0
 assert -2**30<a2<2**30 and 2**30+a1+a2>0 and 2**30-a1+a2>0
 return [b0,b1,b0],[a1,a2]
def generate():
 lines=['/* Generated by tools/vqf_coefficients.py; do not edit numeric literals. */','#pragma once','typedef struct { q30_t b[3],a[2],gyro[5]; uint16_t tau_acc_ms; int64_t rest_w_q20; } fixed_vqf_tune_t;']
 for hz in (2000,1000):
  lines.append(('#if' if hz==2000 else '#elif')+f' FIXED_VQF_SAMPLE_HZ == {hz}U');lines.append('static const fixed_vqf_tune_t fixed_vqf_tunes[3]={')
  for p in PROFILES:
   b,a=coefficients(p['tau_acc_s'],hz);pr=(p['bias_sigma_rest_dps']*100)**2;w=round((pr*pr*hz+pr)*2**20)
   gb,ga=coefficients(math.sqrt(2)/(2*math.pi*p['gyro_lpf_hz']),hz)
   lines.append('    {{'+','.join(map(str,b))+'},{'+','.join(map(str,a))+'},{'+','.join(map(str,gb+ga))+'},'+str(round(p['tau_acc_s']*1000))+','+str(w)+'LL}, /* '+p['name']+' */')
  lines.append('};')
 lines+=['#else','#error "VQF profiles require 1000 or 2000 Hz"','#endif','']
 return '\n'.join(lines)
if __name__=='__main__':(ROOT/'src/fixed_vqf_tuning.h').write_bytes(generate().replace('\n','\r\n').encode())
